### PR TITLE
Add .gitignore file

### LINKED ISSUE #6: Add .gitignore file
We need .gitignore file to automatically ignore files we would like to (like .idea/ or __pycache__/)

### PR DESCRIPTION
**Pull request by zemuvier**
close #6

### CODE REVIEW

**Comment by zemuvier** [comment]
@nbelonogov I don't think everyone want to do this on their local machines, so it's better to use gitignore file (in my opinion, but let's hear another opinions)

**Comment by gaassassins** [comment]
@zemuvier others opinions?...

**Comment by zemuvier** [comment]
@gaassassins what do you think?

**Comment by gaassassins** [comment]
@zemuvier @nikitabelonogov i guess is better one to choose more simple tools for other member in our team and one this ticket is non-priority for us so let's merge it?

**Comment by nikitabelonogov** [comment]
@gaassassins Other option its use global exclude file on local machine. But i think it will be reasonable to use gitignore

**Pull request merged**
